In [1]:
result = str(1) + str(2)
print(int(result) + 3)

15


In [2]:
set([1, 1, 3, 8, 9, 10])[0]


TypeError: 'set' object does not support indexing

In [3]:
summands = [3, 8, 1, 7]                       # Line 1

total = 0                                                # Line 2
while summands:                                # Line 3
    total = total + summands.pop()    # Line 4
    total = total - len(summands)        # Line 5

print(total)         

13


In [4]:
s = 'The squirrel took a nut from a hole in the ground.'
x = 0

for c in s:
    if c == 'a':
        x += 1

In [5]:
jobs = ['CEO', 'data scientist', 'instructor'] # Line 1

if jobs:                    # Line 2
    if 'Pilot' in jobs:     # Line 3
        print(jobs[0])      # Line 4
    else:                   # Line 5
        print(jobs[1])      # Line 6
else:                       # Line 7
    print(jobs[2])          # Line 8

data scientist


In [6]:
x = 1

while x < 1000:
    x = x * 2

In [7]:
def cool_function(an_arg):
    if isinstance(an_arg, str):
        return 'string'
    elif isinstance(an_arg, int):
        return 100

    return type(an_arg)

    if isinstance(an_arg, float): 
        return str(an_arg)
    else:
        return None 
    
print(cool_function(12.3))

<class 'float'>


In [8]:
#true or false if leap year or not

def is_leap(n):
    if n % 400 == 0:
        return True
    elif n % 100 == 0:
        return False
    elif n % 4 == 0:
        return True
    else:
        return False

In [9]:
def calc_default_add(x, y, op="add"):
    if op == 'add':
        return x + y
    elif op == 'sub':
        return x - y
    else:
        print('Valid operations: add, sub')

In [11]:
#function as an argument in anotehr function 
def first_function(value):
    return value * 100

def my_function(another_function):
    return another_function(10)

val = my_function(first_function)
print(val)

1000


In [12]:
class Band(object):
    def __init__(self, band, members, albums, sold, genre):
        self.members = members
        self.band = band
        self.albums = albums
        self.sold = sold
        self.genre = genre

    def print_stats(self):
        return 'band: {} members: {} albums: {} sold: {} genre: {}'.format(self.band, self.members, self.albums, self.sold, self.genre)

Queen = Band('Queen',4,15,105000000,'Rock')
print(Queen.print_stats())

band: Queen members: 4 albums: 15 sold: 105000000 genre: Rock


In [14]:
class Shape(object):
    possible = ['triangle','square','circle','pentagon','polygon','rectangle']

    def __init__(self, label='triangle'):
        self.label = label

    def is_possible(self):
        if self.label in self.possible:
            print('is possible')
        else:
            print('is impossible')

square = Shape(label='square')
wormhole = Shape(label='wormhole')
square.possible.append('wormhole')
wormhole.is_possible()

is possible


In [15]:
def compare(a, b):
    try:
        a_greater = (a > b)
    except:
        a_greater = None
        b_greater = None
    else:
        b_greater = (b > a)
    finally:
        print(a_greater, b_greater)
        
compare(10, 11)

False True


In [16]:
for i in 1 to 10:
    print(i)
    

SyntaxError: invalid syntax (<ipython-input-16-c7a2d2cafef7>, line 1)

In [17]:
def divider(a, b):
    try:
        c = a/b
    else:
        print('divided:', c)
    except:
        print('could not divide numbers')
divider(10, 2)

#else statemnet cannot come before except

SyntaxError: invalid syntax (<ipython-input-17-e454f04cb427>, line 4)

In [19]:
import numpy as np 

my_array = np.array([1, 2, 3])   # Create a vector (rank 1 array) from a list

print(my_array)

print(type(my_array))

np.random.rand(3,1)

[1 2 3]
<class 'numpy.ndarray'>


array([[0.00523885],
       [0.73358246],
       [0.03269195]])

In [20]:
import numpy as np

my_array = np.array([[2,1],[7,4],[5,2],[6,3]])

print(my_array)

my_array.shape  # Return the number of rows and columns.

[[2 1]
 [7 4]
 [5 2]
 [6 3]]


(4, 2)

In [21]:
#finding median and mode 
import numpy as np

from scipy import stats

sample = [3, 75, 98, 2, 10, 3, 14, 99, 44, 25, 31, 100, 356, 4, 23, 55, 327, 64, 6, 20]

mean = np.mean(sample)

median = np.median(sample)

print("mean / median:", mean, median)

mean / median: 67.95 28.0


In [22]:
from scipy import stats

sample = [3, 75, 98, 2, 10, 3, 14, 99, 44, 25, 31, 100, 356, 4, 23, 55, 327, 64, 6, 20]

mode = stats.mode(sample)

print("mode, mount count: ", mode.mode, mode.count)

mode, mount count:  [3] [2]


In [24]:
import pandas as pd
df = pd.DataFrame({'A':['A', 'B', 'C'], 'B':[4, 5, 6]})

group_df = df.groupby('A').mean()

type(group_df)

pandas.core.frame.DataFrame

In [25]:
#importing pandas and matplotlib i think 
import pandas as pd
import matplotlib.pyplot as plt
% matplotlib inline